// Auth action types
export const AUTH_START = 'AUTH_START';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_VERIFY_SUCCESS = 'AUTH_VERIFY_SUCCESS';
export const RESEND_CODE_SUCCESS = 'RESEND_CODE_SUCCESS';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_MESSAGE = 'AUTH_MESSAGE';
export const SAVE_USER = 'SAVE_USER';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';
export const SET_HASH = 'SET_HASH';



// Frontend
export const RESET_REQUEST = 'RESET_REQUEST';
export const REQUEST_START = 'REQUEST_START';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';

export const RESET_CHAT = 'RESET_CHAT';
export const SET_CHAT_HASH = 'SET_CHAT_HASH';
export const CHAT_START = 'CHAT_START';
export const CHAT_SUCCESS = 'CHAT_SUCCESS';
export const CHAT_CLOSE_SUCCESS = 'CHAT_CLOSE_SUCCESS';
export const CHAT_MESSAGE_SUCCESS = 'CHAT_MESSAGE_SUCCESS';
export const RESEND_CHAT_CODE_SUCCESS = 'RESEND_CHAT_CODE_SUCCESS';
export const CHAT_FAIL = 'CHAT_FAIL';



// Backend
export const RESET_DASHBOARD = 'RESET_DASHBOARD';
export const DASHBOARD_START = 'DASHBOARD_START';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAIL = 'DASHBOARD_FAIL';

export const RESET_REQUESTS = 'RESET_REQUESTS';
export const REQUESTS_START = 'REQUESTS_START';
export const REQUESTS_SUCCESS = 'REQUESTS_SUCCESS';
export const REQUESTS_FAIL = 'REQUESTS_FAIL';

export const RESET_B_CHAT = 'RESET_B_CHAT';
export const B_CHAT_START = 'B_CHAT_START';
export const B_CHAT_SUCCESS = 'B_CHAT_SUCCESS';
export const B_CHAT_MESSAGE_SUCCESS = 'B_CHAT_MESSAGE_SUCCESS';
export const B_CHAT_FAIL = 'B_CHAT_FAIL';